esphome:
  name: automotor
  build_path: ./builds/automotor
  platform: ESP32
  board: esp32doit-devkit-v1
 
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
 
logger:
 
api:
  password: !secret api_password
 
ota:
  password: !secret ota_password
 
web_server:
  port: 80


#Wifi info
text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address
    ssid:
      name: Wifi SSID

# Restart the device
switch:
  - platform: restart
    name: "Restart"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    id: button01
    on_press:
      then:
        - light.toggle: motor01
  - platform: gpio
    pin:
      number: GPIO18
      mode: INPUT_PULLUP
      inverted: True
    id: button02
    on_press:
      then:
        - light.toggle: motor01

output:
  - platform: gpio
    pin: GPIO13
    id: output01
    inverted: True


light:
  - platform: binary
    name: "Motor"
    id: motor01
    output: output01

time:
  - platform: sntp
    id: sntp_time
    timezone: Asia/Kolkata
    servers: 0.pool.ntp.org